global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
      monitor: 'lab'
scrape_configs:
  - job_name: 'prometheus_exporter'
    static_configs:
      - targets: ['localhost:9394']
